import { Rubik } from "next/font/google";
import "./globals.css";
import { MyThemeProvider } from "@/components/ui/MyComponents/ThemeProvider";
import { CustomProvider } from "@/redux/Provider";

const rubik = Rubik({
	subsets: ["latin"],
});

export const metadata = {
	title: "UniVerse",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			suppressHydrationWarning>
			<body className={rubik.className}>
				<CustomProvider>
					<MyThemeProvider
						attribute="class"
						defaultTheme="light">
						{children}
					</MyThemeProvider>
				</CustomProvider>
			</body>
		</html>
	);
}
