import { Rubik } from "next/font/google"
import "./globals.css";
import { MyThemeProvider } from "@/components/ui/MyComponents/ThemeProvider";
import { MainMenu } from "@/components/ui/MyComponents/MainMenu";

const rubik = Rubik({
	subsets:["latin"]
})

export const metadata = {
	title: "UniVerse",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={rubik.className}>
				<MyThemeProvider attribute="class" defaultTheme="system">
					{children}
				</MyThemeProvider>
				<MainMenu />
			</body>

		</html>
	);
}
